mainMenu = ['Look for a recipe', 'Translate an ingredient' ]
recipeMenu = ['Check details', 'Send me the recipe per email', 'Go back to previous menu']
chooseMeal = ['Choose a meal to get recipes: e.g. "Carbonara": ']
detailMenu = ['Send me the recipe per email', 'Send me the shopping-list per email', 'Go back to previous menu']
numberOfRecipes = ['Optional: How many results do you want? Press enter to skip!: ']
email = ["Please enter a valid email address: "]
translator = ["Please enter a word / sentence that you want to translate: "]